### ISSUE TITLE
Key Size for LFSR based CS encryption

### ISSUE THREAD

**Issue by gajrajkuldeep** [compressedsensing/compressed_sensing#2]
Right now there two LFSR of length 16 and NFSR of length 8 for sensing matrix generation. Therefore, Key size is 40 bit which is not secure against the brute-force attack. You need to increase LFSR and NFSR length. For experimentation, Key size should be more than 90, this can be achieved by selecting polynomials of degree 30 or more for LFSR and NFSR

**Comment by kasperlauge** [comment]
Okay, we increased the LFSR's for the final measurements, but what do you suggest we should use for NFSR? It seems to be difficult to find good examples of NFSR's bigger than 24. What do you think would be a good pick for NFSR?

**Comment by kasperlauge** [comment]
Atm you can see I have just picked one polynomial, but I guess we cannot be sure that is a good polynomial. What are you going to do? And does it matter, because the energy consumption might not be that different?

**Comment by gajrajkuldeep** [comment]
For experimentation, I think you can choose LFSRs with lengths  64 and 40, and NSFR length 20 or 24. Then the key length will be around 128 which is ok.

**Comment by kasperlauge** [comment]
I think two 64 bits LFSR and one 16 bit LFSR would probably be a lot easier to implement. Would that be a good enough choice aswell?

**Comment by gajrajkuldeep** [comment]
yes, you can go for an 8bit NFSR and two 64 bit LFSRs if it suits your hardware design.

**Comment by kasperlauge** [comment]
Cool! That should be done now :)

**Comment by gajrajkuldeep** [comment]
Good
